kumuluzee:
  name: kp-rest-service
  version: 1.0.0
  env:
    name: dev
  openapi:
    enabled: true
  # Database
  datasources:
    - jndi-name: jdbc/kpRestService
      connection-url: jdbc:postgresql://localhost:5431/kp-rest-service
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/kpRestService
    logs:
      enabled: true
      type: liveness
      level: FINE
      period-s: 3